apiVersion: apps/v1
kind: Deployment
metadata: 
  name: django-deployment 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: subrato123/django-app
        ports: 
        - containerPort: 8000