apiVersion: v1
kind: Service
metadata: 
  name: django-Service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080