apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-k8s.fullname" . }}
  labels:
    {{- include "project-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30080
      {{- end }}
  selector:
    {{- include "project-k8s.selectorLabels" . | nindent 4 }}